### ISSUE TITLE
Attribute-hooks

### ISSUE THREAD

**Issue by mindplay-dk** [jorgebucaran/superfine#117]
Support for `style` diffing (setting `style` to an `object` value) was [removed](https://github.com/jorgebucaran/ultradom/commit/2a8f478841a6088505cf2f0ddc8d67bf0edb2bdd), and there is currently no way for a library to add it back in.

As discussed [here](https://github.com/jorgebucaran/ultradom/commit/2a8f478841a6088505cf2f0ddc8d67bf0edb2bdd#commitcomment-29087144) this could be solved by reconsidering support for modularity, which was previously proposed in #86. (this PR is outdated, and the approach is probably wrong, see below.)

Note that the approach in that PR was based on use a global registry, which should be avoided, as discussed in the comments above.

Needs a detailed proposal, but one idea is to make this feature available via currying to avoid global state. You would get a default instance of the `render` function with only the built-in attribute-handlers - as well as a factory-function, which you could use to generate another instance of `render` with additional attribute-handlers registered in the instance of it, to avoid global state and side-effects.

For example:

```js
import * as ultradom from "ultradom";

export const render = ultradom.render.with({
  style: (el, value, oldNode, newNode) => {
    // diff and apply style properties
  }
});
```

That's just an idea - this needs a more detailed proposal.

**Comment by jorgebucaran** [comment]
@mindplay-dk Is using a function that produces a `style` string out of the question?

**Comment by mindplay-dk** [comment]
> Is using a function that produces a `style` string out of the question?

I suspect it'd be more complex than the simple diffing of style-properties the way it was before.

Also doesn't make sense in terms of performance - you'll diff objects and compose strings just to have DOM immediately parse those strings back into values.

Either way, regardless of how it's implemented, the point of your removing this was, it's outside the scope of the library, right?

So I guess the first question how does someone plug-in this feature? If we can answer that, then it becomes totally open-ended: you can choose no style-support, hard-code it for your use-case, diff objects, compose strings, whatever :-)

**Comment by jorgebucaran** [comment]
Some ideas:

- Options (third argument to render).
- New lifecycle event `onpatch`, called both before oncreate and onupdate.
- Support this via oncreate/onupdate.

**Comment by jorgebucaran** [comment]
Another attribute that would benefit from this system is class/className.

**Comment by mindplay-dk** [comment]
> New lifecycle event `onpatch`

Doesn't help implement support for `style` *globally* in a library/framework that uses ultradom?

> via oncreate/onupdate

Same.

> Options (third argument to render).

Stateless and functional - yeah, that sounds good.

So, taking from `updateAttribute` signature (minus the without the attribute `name`, which is a given) a hook implementation in an enhanced `render()` function might look something like:

```
import * as ultradom from "ultradom"

export function render(node, container) {
  ultradom.render(node, container, {
    style: (element, value, oldValue, isSVG) => {
      // ...
    }
  });
}
```

Alternatively, taking from `updateElement` rather than `updateAttribute` is maybe a bit harder to understand, but more low-level and flexible, as it allows you to inspect other attributes besides the one that triggered the hook - something like:

```
import * as ultradom from "ultradom"

export function render(node, container) {
  ultradom.render(node, container, {
    style: (element, oldAttributes, attributes, isSVG) => {
      // ...
    }
  });
}
```

Not sure which is better - the first is easier to understand, but a bit less flexible and doesn't allow hooks to depend on other attributes. For example, if implementing a hook for the `value`-attribute on `<select>`-elements, you might need access to `name`-attribute or something. Somebody might want to access `key` for some reason maybe, not sure - perhaps better not to block any use-cases?

(by the way, the argument order in these examples is consistent with the functions in ultradom, which are currently a bit inconsistent: `value, oldValue` vs `oldAttributes, attributes`.)

**Comment by jorgebucaran** [comment]
I was thinking, why not style components using one of the myriad of CSS-in-JS solutions, such as a https://github.com/morishitter/picostyle?

**Comment by frenzzy** [comment]
Because it is overhead when you want to animate only few style rules?
`<div style={{ left }} />` uses `element.style.left = left`
vs
`<div class={css("left: ${left}")} />` generates class name, inserts is to the document, updates class name

**Comment by mindplay-dk** [comment]
> why not style components using one of the myriads of CSS-in-JS solutions

"myriad" is right - just picking one would take days.

Why the opposition against supporting something so trivial?

**Comment by jorgebucaran** [comment]
Style support is back.

**Comment by mindplay-dk** [comment]
> Style support is back.

And now it's gone again. 😏
