### ISSUE TITLE
Support for JSX

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#120]
In the README it mentions that this ever-differently named project supports JSX. In fact it does not. 
Here's an example using the default `h` function:

```javascript
function Title(message) {
  return h(
    'h1',
    {},
    `Hello, ${message}!`
  )
}
let title = null
title = render(title, Title('Joe'), document.body)
```
This works as expected. Now if we change this to use JSX:

```javascript
function Title({message}) {
  return (
    <nav>
      <h1>Hello, {message}!</h1>
    </nav>
  )
}
let title = null
title = render(title, <Title message='Joe' />, document.body)
```
This does not work. Instead we get an error:

```
InvalidCharacterError: The string contains invalid characters.
```
This points to line 48.
That because of changes made to the `h` function. This is because, unlike the `h` function, a JSX tag returns a function. In Hyperapp, you check for a name of value "function". In this lib you do not. Currently the `h` function just returns a `vnode`:

```javascript
return {
  name: name,
  attributes: attributes || {},
  children: children,
  key: attributes && attributes.key
}
```
You could change it to this to restore support for JSX tags:
```javascript
if (typeof name === 'function') {
  return name(attributes || {}, children)
} else {
  return {
    name: name,
    attributes: attributes || {},
    children: children,
    key: attributes && attributes.key
  }
}
```

**Comment by jorgebucaran** [comment]
@rbiggs JSX pure functional components (or JSX tags are you call them) are no longer natively supported. 

Here is a minimal way to add it back. 

```js
import { h as createElement } from "superfine"

export const h = (name, attributes, ...children) => 
   typeof name === "function"
        ? name(attributes, children)
        : createElement(name, attributes, children)
```

**Comment by jorgebucaran** [comment]
Do you think we should add it back by default? 

```js
return name(attributes || {}, children)
```

...is just one possible way to implement it. Users may want a different signature, for example:

```
return name(Object.assign({}, attributes, { children }))
```

etc.

**Comment by rbiggs** [comment]
Well, that is your call. I just noticed the lack of JSX tag support today with the new new name ;-) I think most people would expect JSX tags to just work, same as they do in Hyperapp, Preact, Inferno, React, etc. A hypersrcipt function that doesn't handle JSX tags just don't feel that hyper. Better to ask some of your collaborators: @andrewiggins, @zaceno, @acstll and @mindplay-dk.

**Comment by mindplay-dk** [comment]
> Do you think we should add it back?

IMO, it's so little code, there's no real point in not having support for that.

And I think it matters, if you want someone to be able to try it out and play around immediately.

Likely, most people interested to begin with are looking to use JSX - there's no reason to discourage them.

**Comment by acstll** [comment]
Without knowing anything, I would say "add it back". It should just work.

But I would also like to know the reasoning behind removing it in the first place. (Maybe there's an issue with that information?).

To be honest the last time I used this library for something going to production it was still called picodom! I'm sure I would use it again if an opportunity shows up. And functional components is something I would like to use out of the box.

Just my 2 cents. (It makes me sad I can't write things down sarcastically just as @rbiggs)

**Comment by jorgebucaran** [comment]
@acstll @rbiggs I just want to clarify Superfine **supports** JSX out of the box.

```js
render(null, <h1>Hello</h1>, document.body) // It works!
```

What's _not_ supported out of the box are functional components.

```jsx
const Title = props => <h1>{props.text}</h1>

render(null, <Title text="Hello" />, document.body) // Doesn't work.
```

...because I can't make up my mind what the component signature should be. 

- (props, children)
- ({ ...props, children })

**Comment by acstll** [comment]
> I just want to clarify Superfine supports JSX out of the box.

Yep, that's clear. :-)

> ...because I can't make up my mind what the component signature should be.

I can't relate to that. If there's no big difference with the implementation, I would go with `({ ...props, children })` because: (1) it's closer to React's API, where `children` is part of props (what most peeps would expect?, correct me if I'm wrong in both assumptions, it's been also long since I used React), and (2) it's more terse, one argument it's simpler to handle than two (I guess?). Let's discuss the pros and cons of each?

**Comment by jorgebucaran** [comment]
0b9667a38fff30f9f68694bdbaea8ac2af477d62
