### ISSUE TITLE
Difference/advantages to superfine over Hyperapp/React?

### ISSUE THREAD

**Issue by RyanNerd** [jorgebucaran/superfine#122]
I'm not being surly -- I am just asking. I've used:
* Angular
* Ember
* React 

I like React the most out of these three. On a whim I decided to look into other frameworks to see how they stack up against the frameworks I've used. I came to this site from [here](https://dev.to/mindplay/comment/1n7d) and to be quite honest superfine appears to be Hyperapp clone but not as mature. Am I wrong?

**Comment by jorgebucaran** [comment]
Superfine is similar to React from that list, but it's very different to Angular and Ember.

Superfine is lower level than React and Hyperapp as it doesn't have an opinion on state management or a stateful component system. Hyperapp is going through some changes and 2.0 will add new abstractions which Superfine will never have.

There's also preact (4kB), a pre-fiber React clone. And Inferno (8kB), similar as well, but more advanced than preact. Both have a way to set the state (and cause redraws), i.e., `setState` and promote local component state. 

Superfine only exposes a `render` function.

Hope this helps. If you have further questions, feel free to ask. 

👋

**Comment by RyanNerd** [comment]
@jorgebucaran Thanks for taking the time to give me a detailed answer. I appreciate it.
