### ISSUE TITLE
unpkg.com version does not match current Github version

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#125]
The version of Superfine on https://unpkg.com/superfine@5.0.1/dist/superfine.js does not match the current version of Superfine 5.0.1 on Github. Specifically, the unpkg version is missing everything for recycling and JSX functional components. I believe that's because you need to bump the version for the previous commit with these features to hit unpkg. Since recycling and full JSX support are new features, I would suggest a minor version update: 5.1.0, if you want to stick to semantic versioning rules.

**Comment by jorgebucaran** [comment]
Yep, I just need to cut a new release. I'll get to it very soon. 👍

**Comment by jorgebucaran** [comment]
I'm delayed because of other work and Hyperapp V2.

In the meantime grab it from https://rawgit.com/jorgebucaran/superfine/master/src/index.js 🙏

**Comment by jorgebucaran** [comment]
Should be working now!

https://github.com/jorgebucaran/superfine/releases/tag/6.0.0
