### ISSUE TITLE
Problem with Keyed Lists

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#126]
I'm seeing a problem with dynamic keyed lists. When I add a new item the first time, the new item is added. When I add a second item, it adds that plus the previous item to the list, when I add a third item, it adds the first, second and third new items to the list. At the same time, the data being produced for the list is accurate. Because the number of items in the updated list do not match the data, you cannot accurately delete a list item. The virtual node list doesn't match the data or what's in the DOM. @jorgebucaran, have you tried creating a todo list with this latest version?

Here's what the resulting list looks like as I add `111`, `222` and `333`:
<img width="368" alt="screen shot 2018-06-29 at 7 13 00 am" src="https://user-images.githubusercontent.com/249218/42097119-2292d832-7b6c-11e8-9d60-1d00956e75ba.png">

<img width="377" alt="screen shot 2018-06-29 at 7 13 26 am" src="https://user-images.githubusercontent.com/249218/42097122-27ba5af6-7b6c-11e8-9e8c-05e6598d21f6.png">

<img width="368" alt="screen shot 2018-06-29 at 7 13 58 am" src="https://user-images.githubusercontent.com/249218/42097131-2f0dc40a-7b6c-11e8-8dca-6981e086aaeb.png">

 
The example where this is happening worked fine with Ultradom 3.x. Of course I updated it to work with the new call signature for the `render` function. I can't currently post a public example since unpkg doesn't point to this version yet.

**Comment by jorgebucaran** [comment]
@rbiggs Could you please create a CodePen with the issue?

**Comment by rbiggs** [comment]
Here's the original pen that the other list was based on. It's using Ultradom 2.3.4, back when it worked with JSX: https://codepen.io/rbiggs/pen/oyJJNV?editors=0010. Fork it and see if you can get it to work. I haven't had any luck, but I might be overlooking something really minor. 🙄

**Comment by jorgebucaran** [comment]
@rbiggs Seems to be working alright with the latest master. It's probably a false alarm. I'll close here with a CodePen example as soon as I published a new version. Sorry for the trouble! 🙇 

![2018-06-30 11 42 25](https://user-images.githubusercontent.com/56996/42120702-d1086898-7c5a-11e8-903d-c60636e266d1.gif)

**Comment by rbiggs** [comment]
Ugh! Here's an update about what was happening. I didn't realize you have to reassign the component with every update. 🤭 So, I had this for the first render:
```javascript
let list = render(null, <List data={fruits} />, document.querySelector('#root'))
```
But in the `addItem` function I had this:
```javascript
function addItem() {
  const input = document.querySelector('input')
  const value = input.value
  if (value) {
    fruits.push({ key: newKey++, name: value })
   // I assumed that render would automatically reassign the result here:
    render(list, <List data={fruits} />, document.querySelector('section'))
    input.value = ''
  } else {
    alert('Please provide a value before submitting.')
  }
}
```

This works the first time you add something, but after that it heads south quick. In reality that second render needs to reassign the result of the render back to the `list` variable:

```javascript
if (value) {
  fruits.push({ key: newKey++, name: value })
  // Correct way to re-render the list:
  list = render(list, <List data={fruits} />, document.querySelector('section'))
  input.value = ''
}
```
With that change updates from adding a new item work as expected. 🍶

Same issue with the `deleteItem` function. I think you need to mention this fact somewhere in the README that when rerendering a component you need to reassign it to the same variable. Otherwise a lot of people are going to make the same dumb mistake. 🤔

Otherwise, I'm totally loving the changes you've made to Pico-ultra-fine. 🎉🥂 I hadn't really used it since 2.4.9 because of lack of JSX support, etc. Now it feels like 🏋️‍♂️.

**Comment by mindplay-dk** [comment]
> Pico-ultra-fine

Now *there's* a name we can finally commit to 😂

**Comment by jorgebucaran** [comment]
Superfine, superfine, superfine! :)
