### ISSUE TITLE
What happened to onremove?

### ISSUE THREAD

**Issue by van-nguyen** [jorgebucaran/superfine#128]
It was a really handy feature, seems to have gone missing when upgraded from ultradom.

**Comment by rbiggs** [comment]
@van-nguyen, check out the [lifecycle events](https://github.com/jorgebucaran/superfine#lifecycle-events) in the README.

**Comment by jorgebucaran** [comment]
@van-nguyen onremove is coming back after I cut a new release. It's definitely in master now! :)

**Comment by jorgebucaran** [comment]
@van-nguyen onremove is coming back after I cut a new release. It's definitely in master now! :)

**Comment by rbiggs** [comment]
Oh, I see, @jorgebucaran, you haven't bumped the version number yet.

**Comment by jorgebucaran** [comment]
Thanks! Will do when everything is ready. 🙏

**Comment by jorgebucaran** [comment]
A new version is out and `onremove` is back in the game! 🏀 

https://github.com/jorgebucaran/superfine/releases/tag/6.0.0
