### ISSUE TITLE
Bug: children is doubled when using "Pure Components"

### ISSUE THREAD

**Issue by van-nguyen** [jorgebucaran/superfine#129]
When I use the new `h` function, it is meant to support Components out of the box, so I gave it a try. but seems like the result is the children is doubled.

But when I revert back to the previous hack using ultradom

```js
window._h = (name, props, ...children) => typeof name === 'function' ? name(props, children) : h(name, props, children);
```

It was like it's meant to. Let me know if you need further details.

**Comment by rbiggs** [comment]
Could you post a simplified version of the code producing a doubling of children? I suspect you aren't passing in the reference to the first patch on subsequent patches. I made that mistake first time.

**Comment by jorgebucaran** [comment]
@van-nguyen I don't know about doubling children. Sounds like a bug! 😨

But JSX pure component support will land in the next release. It's already in master.

**Comment by van-nguyen** [comment]
Okay I understood why it happens now, here is a codepen to demonstrate: https://codepen.io/van-nguyen/pen/gzZZrZ?editors=1010

Before `children` was not exposed to `props`, but now you can access `children` directly from `props` or from the 2nd param. As a result when you do `{...props}` it merges the children into the already existing `props.children`. This was not the behaviour from before.
