### ISSUE TITLE
New Merge function.

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#130]
I noticed you've changed how the merge function works. You now use an array instead of an object:
```javascript
var target = []
```
Then when you use it, you also use a for in loop:
```javascript
for (var i in merge(lastValue, nextValue))
```
For in loops with arrays are notorious for various unexpected issues and are known for not being very performant compared to alternative means of looping [Stackoverflow](https://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-a-bad-idea), [The Problems with for...in and JavaScript Arrays](http://adripofjavascript.com/blog/drips/the-problem-with-for-in-and-javascript-arrays.html). I'd suggest using `map` instead. It's more performant, easier to read and doesn't suffer from issues that for of can cause:

```javascript
merge(lastValue, nextValue).map(nextValue => {
  var style = nextValue == null || nextValue[i] == null ? "" : nextValue[I]
  //...
})
```
This is just a friendly suggestion, not an OMG we gotsa have it!

**Comment by jorgebucaran** [comment]
@rbiggs Good catch, that's only a typo. Will fix it soon. 👍

**Comment by mindplay-dk** [comment]
> I'd suggest using `map` instead. It's more performant

Huh? No it isn't.

https://jsperf.com/map-reduce-named-functions/2

**Comment by jorgebucaran** [comment]
Interesting trivia: I didn't notice this error until now and have been benchmarking superfine all this time with it! 😄

**Comment by rbiggs** [comment]
@mindplay-dk, that JSPerf shows exactly what I said. That a `map` is faster than a `for in`. I didn't say `map` was the most performant out of every possible way to loop. `map` is the native method for looping on an array without side effects. If you want side effects, then there's `forEach`. Although developers are averse to use `forEach` for looping over arrays, it's usually faster than `map`. The fact is, most developers would rather use a `map` on an array than a `for` loop because the resulting code is cleaner looking and easier to reason about. However, since you brought up JSPerf, here's one where `map`, `forEach` and `for` are neck and neck: [.map() vs .forEach() vs for()](https://jsperf.com/map-vs-foreach-logging/2).

And one thing about JSPerf, a test can vary extremely due to minor tweaks in the test algorithm, as you can see when you examine all the forks of a test. They also vary quite a bit from one browser to another or from one browser version to another. Case in point, check out the difference in performance for the map-vs-foreach-vs-for. Notice how ridiculously fast Safari is for all three. Normally it's believed that Chrome is the speed demon, but in this case Safari is running loops at light speed. Conclusion, it you have a lot of users on Safari (iOS), you really don't have to worry about loop performance.

<img width="884" alt="foreach-map-for" src="https://user-images.githubusercontent.com/249218/42197076-eed9f300-7e35-11e8-9e4d-ebfc49daedc3.png">

The conclusion is that you should never make an architectural decision based on a JSPerf example. They are interesting experiments in trivially controlled situations and do not represent real world use.

**Comment by jorgebucaran** [comment]
_Slightly off-topic_: I've noticed jsperf behave erratically depending on the order of my tests. When I tested the bad merge function using [] vs the one using {}, the first test outperformed the other consistently by a "small" margin (2k~3k ops).

But when I added a new test snippet, essentially `Object.assign({}, a, b)`, [] merge and {} merge, the {} beat them both by a huge margin >100k ops IIRC.

**Comment by rbiggs** [comment]
See, that's the whole thing about JSPerf. It makes it really easy to put together misleading tests. One thing, if you are going to use JSPerf to determine an architectural direction, you really need to test on as many browsers as possible: IE11, MSEdge, Firefox, Chrome and Safari. Browsers optimize different things, resulting in sometimes wildly different results for the same perf.

**Comment by jorgebucaran** [comment]
💯that.

**Comment by mindplay-dk** [comment]
> if you are going to use JSPerf to determine an architectural direction, you really need to test on as many browsers as possible

I only use it to spot drastic differences in micro-performance in the leading browsers.

I'm quite surprised that `map` is faster than bare loops - it must be clever enough to inline the function and avoid the call entirely, though I wonder how/why that would be faster than an actual loop. Go figure :-)

**Comment by jorgebucaran** [comment]
A new version is out! Thanks, @rbiggs, for discovering my mistake.
