### ISSUE TITLE
Clean up h function

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#131]
I noticed some you're doing an `isNull` check on `props` and` props.children` in the `h` function:

```javascript
  var node
  var rest = []
  var children = []
  var length = arguments.length

  while (length-- > 2) rest.push(arguments[length])
  
  // Checking nullness of props and props.children:
  if (!isNull((props = props || {}).children)) {
    rest.push(props.children)
    delete props.children
  }
```
You could make that a bit tidier by giving `props` a default value:

```javascript
  var node
  var rest = []
  var children = []
  var length = arguments.length
  // Default value for props:
  props = props || {}

  while (length-- > 2) rest.push(arguments[length])

  // Simplified check for props.children:
  if (!isNull(props.children) {
    rest.push(props.children)
    delete props.children
  }
```

**Comment by jorgebucaran** [comment]
@rbiggs That's exactly what it's happening, I just obfuscated the code because...! 😄 

```js
if ( isNull( ( props=props||{} ).children ) ) )  {...}
```

...is the same as:

```js
props = props || {}
if ( isNull( props.children ) )  {...}
```

Now we should debate which one is more readable.

**Comment by rbiggs** [comment]
ha ha, actually, that's what I was saying. 🤷‍♂️ But to me, declaring a default inside the `isNull` feels, um, messy. But then, ECMAScript 2015 does enable that with default param values, so... Whatever.

**Comment by jorgebucaran** [comment]
@rbiggs I admit I am golfing the code a bit here for no particularly good reason.

**Comment by mindplay-dk** [comment]
> I admit I am golfing the code a bit here for no particularly good reason.

please stop 😂
