### ISSUE TITLE
isNull or isNullOrUndef

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#133]
I noticed you have a function called `isNull` that checks if the argument is null or undefined. Seems like it should be named something more generic like `isNulish` or like Inferno uses, `IsNullOrUndef`. A rose by any other name would be just as null, he he. 😌

**Comment by leeoniya** [comment]
it would also be faster as

```js
var isNull = function(any) {
  return any == null;
}
```

**Comment by frenzzy** [comment]
also this version
```js
if (value != null) {
if (value == null) {
```
is more readable and cleaner than
```js
if (!isNull(value)) {
if (isNull(value)) {
```

**Comment by rbiggs** [comment]
Inferno has:

```javascript
export function isNull(o: any): o is null {
  return o === null;
}
export function isUndefined(o: any): o is undefined {
  return o === void 0;
}
export function isNullOrUndef(o: any): o is undefined | null {
  return isUndefined(o) || isNull(o);
}
```

**Comment by jorgebucaran** [comment]
@leeoniya https://jsperf.com/checkingfornullandundefined

**Comment by mindplay-dk** [comment]
I'm with @frenzzy on this one: `value == null` is idiomatic Javascript for "is null or undefined".

**Comment by mindplay-dk** [comment]
@rbiggs maximum overkill ;-)

**Comment by rbiggs** [comment]
Well, but Inferno uses all three, depending what it's doing. By the way folks, JSPerf is showing its age. It hasn't been maintained well since it launched 10 years ago and is getting creaking. @jorgebucaran, here's a modern, well-maintained alternative: [MeasureThat](https://www.measurethat.net). Happy perfing! There's also [jsbenchmarks](http://www.jsbenchmarks.com), but I haven't really used it before.

Forgot to mention, JSPerf and others are based on [BenchMarkJS](https://benchmarkjs.com), which you could use to set up your own perf, petal to the metal. And, be aware that any perfing tool will face [perf challenges](https://www.quora.com/Are-jsPerf-results-reliable?share=1eff45aa&srid=01By).

**Comment by jorgebucaran** [comment]
Went back to my old habits. 😄
