### ISSUE TITLE
Null or "" for root doesn't work anymore

### ISSUE THREAD

**Issue by shirotech** [jorgebucaran/superfine#143]
When I patch an element with either null or "", I was expecting to be empty, but it's throwing errors. This was not the case for previous versions. Let me know if need a codepen. Cheers.

**Comment by jorgebucaran** [comment]
@van-nguyen Yeah, I know. What is your use case?

**Comment by van-nguyen** [comment]
One major use case is for Modals and popups. Since we don't have unmount.

**Comment by jorgebucaran** [comment]
Please join the convo in https://github.com/jorgebucaran/superfine/issues/136.
