### ISSUE TITLE
recycle is missing from TypeScript definitions

### ISSUE THREAD

**Issue by wanton7** [jorgebucaran/superfine#157]
Function recycle is missing from TypeScript definitions. I would create a Pull request, but my Git skills are non existent. Out company is still using SVN :(

**Comment by jorgebucaran** [comment]
@wanton7 No problem. Can you post the code in this issue?

**Comment by wanton7** [comment]
@jorgebucaran  Here, but description might need fine tuning.

```
/**
 * Recycle DOM element container.
 *
 * @param {Element} container A DOM element where DOM elements are recycled from.
 **/
export function recycle(
    container: Element
): VNode
```

**Comment by jorgebucaran** [comment]
Recycle is now baked in Superfine 7. 🎉
