### ISSUE TITLE
Is using custom `events` property for DOM element really future proof?

### ISSUE THREAD

**Issue by wanton7** [jorgebucaran/superfine#159]
Browsers could add `events` property for DOM elements in the future and break superfine. Because  standard DOM element properties follow camelCase naming convention using snake_case convention for property name like `superfine_events` instead should be quite future proof.

**Comment by jorgebucaran** [comment]
Or `_events`. I think I can address that in a future release. No problem.

**Comment by mindplay-dk** [comment]
I never noticed this change. @jorgebucaran I thought you were dead set against injecting anything into DOM elements? (if not, then why not go all the way and store last propert state in there as well? and remove the need for manual state management on the consumer's part like I've been pushing for in the past?)

**Comment by jorgebucaran** [comment]
I'm not dead set against it. This one makes sense.

**Comment by jorgebucaran** [comment]
I'm not dead set against it, but I'm going to allow this one.
