### ISSUE TITLE
Is superfine a shared core among hyperapp v1/v2 ?

### ISSUE THREAD

**Issue by stken2050** [jorgebucaran/superfine#160]
I found this repo having known as a core of[ `hyperapp`](https://github.com/jorgebucaran/hyperapp)
.
hyperapp is during the migration from v1 to v2, and I would like to know if this superfine is a shared core of both. Thanks.

**Comment by jorgebucaran** [comment]
@stken2050 Hyperapp's virtual DOM is based on Superfine, so we can say they both share the same core, although neither uses the other as a dependency.

**Comment by stken2050** [comment]
I understand. Thanks a lot for your prompt response. @jorgebucaran

**Comment by jorgebucaran** [comment]
@stken2050 My pleasure. Thanks for asking!

**Comment by jorgebucaran** [comment]
@stken2050 That's the plan! 💯

**Comment by stken2050** [comment]
@jorgebucaran Hello again.

I'd like to advertise my newly project :  [unlimitedjs](https://stken2050.github.io/unlimitedjs/) ([superfine](https://github.com/jorgebucaran/superfine/) + [timeline-monad](https://stken2050.github.io/timeline-monad/)).

When you started [Hyperapp](https://github.com/jorgebucaran/hyperapp), how did you obtain the awareness of your project among frontend developers eco?

Thanks!

**Comment by jorgebucaran** [comment]
@stken2050 I used social networks like Reddit, Twitter, and so on. Good luck with your project! 👋
