### ISSUE TITLE
Reference from a new virtual DOM framework project based on superfine

### ISSUE THREAD

**Issue by stken2050** [jorgebucaran/superfine#162]
Hi, I created a new virtualDOM framework based on superfine.
I mentioned this project in
https://stken2050.github.io/unlimitedjs/#_unlimitedjs
and
https://stken2050.github.io/unlimitedjs/#_vitural_dom_superfine

I would be grateful if you could check accuracy of the mentioning to this project.

Thanks!

**Comment by jorgebucaran** [comment]
@stken2050 Looks cool. Thanks for using Superfine. 🎉

**Comment by stken2050** [comment]
@jorgebucaran Thanks for your quick review and providing this great project! :)
