### ISSUE TITLE
Is there any way superfine JSX/HyperScript code work on iOS/Android natively like React-Native?

### ISSUE THREAD

**Issue by stken2050** [jorgebucaran/superfine#163]
Is there any way superfine JSX/HyperScript code work on iOS/Android natively like [React-Native](https://facebook.github.io/react-native/)?

**Comment by jorgebucaran** [comment]
That would be super fine, but no, there isn't. 😄

**Comment by stken2050** [comment]
> That would be super fine, but no, there isn't.

Thanks!
