### ISSUE TITLE
Missing superfine.d.ts

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/superfine#168]
I noticed that in commit 4b3593b23cc49e367aa8d019af84105e2bd81c6f you deleted the `superfine.d.ts` file, but you left the reference to it in the `package.json` file. Was the deletion intentional or do you not want there to be a typings file now? If not, you should remove the reference to it from the `package.json` file.

**Comment by jorgebucaran** [comment]
@rbiggs Only that I can't maintain it. If you're up to the challenge and can keep an eye on it going forward, I'll accept a PR.

**Comment by jameswilddev** [comment]
Just to let anyone who finds this know: I've submitted a PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45019) which should hopefully allow for a community maintained set of type definitions at @types/superfine.
