### ISSUE TITLE
Is v6 officialy depredated?

### ISSUE THREAD

**Issue by k1r0s** [jorgebucaran/superfine#170]
related https://github.com/jorgebucaran/superfine/issues/167

As a mather of fact v7 dropped several features and promotes -forces- developers to use pure functional approaches or custom elements. I do have a library that heavily relies on lifecycles to provide stateful components, so I can't upgrade to v7 now (and likely to be pined on v6 forever). 

My question is whether or not v6 will receive patch releases.

Soo, if you don't have time or you're half will on this I can contribute to help. I beg you to create a branch from v6 :)

Thoughts?

**Comment by jorgebucaran** [comment]
> @k1r0s My question is whether or not v6 will receive patch releases.

Basically, I don't have a problem with that, but does it require creating a branch?

**Comment by k1r0s** [comment]
nope, is up to you how to organize stuff. Thanks
