### ISSUE TITLE
Usage of Props

### ISSUE THREAD

**Issue by kethan** [jorgebucaran/superfine#171]
How to use props and subscription like in hyperap?

**Comment by jorgebucaran** [comment]
@kethan Hyperapp subscriptions (declarative layer to manage event streams), is a high-level abstraction not available for Superfine. This library is only a virtual DOM. If you want something like Hyperapp subscriptions, you're free to create your own.

**Comment by kethan** [comment]
Ok thanks. But how do I use props ?

**Comment by jorgebucaran** [comment]
@kethan You need to be more specific, your question doesn't make sense without some context.
