### ISSUE TITLE
patch doesn't replace id of target node

### ISSUE THREAD

**Issue by vuhg** [jorgebucaran/superfine#173]
I use `superfine` and with `babel-plugin-htm`. Both are latest version.

As you can see, `patch` doesn't remove the div's id.
Is that intended?

<img width="512" alt="Screen Shot 2019-08-28 at 8 03 44 PM" src="https://user-images.githubusercontent.com/54054422/63858503-c90d0e00-c9cf-11e9-969b-1138565045e9.png">
<img width="554" alt="Screen Shot 2019-08-28 at 8 04 05 PM" src="https://user-images.githubusercontent.com/54054422/63858505-c9a5a480-c9cf-11e9-9be6-bad115ee8990.png">

**Comment by vuhg** [comment]
As Jorge said in slack, this is intended behavior.

**Comment by jorgebucaran** [comment]
Superfine/Hyperapp recycle existent content (the node you give it). That's why this happens. If you change the ID to, let's say `"foo"` it'll change it to `"foo"`.

Long story short, this is expected behavior.
