### ISSUE TITLE
Minimum example of a table with some sorting

### ISSUE THREAD

**Issue by mike-ward** [jorgebucaran/superfine#181]
Fooling around and wrote this quick table sample. Click on the Author to sort.

https://is.gd/sb3Bqt

**Comment by jorgebucaran** [comment]
Excellently done! Thank you for sharing, @mike-ward. 👋 

Here's [my revision](https://flems.io/#0=N4IgtglgJlA2CmIBcBWA7AOgJwCYA0IAzvAgMYAu8UyIGAFuWLCAaQPYB2hbCN7ssAIYAHYtQKFSAJx7MkAbQAMeRQF0CAMwgJCyeaA6CwiJLQZMWIdh0o2aAHgCEAEQDyAYQAqATQAKAUQACc1gAPgAdDnsQwKEOAHMAXnCQeA4UiI5AwOj4QShM7Oz7WAgOAGtIoqKpEmSicgBPHTp4eHIUqurg2o16hnJRJAB6YdIoDgwAK0IoEggANykMDnbhjmEwYYABeAAPI2EEOYX1+AB3DFJCQm2ARgwHnDPLyEnrwk6souHCovtJFIIMJyIFCFJSP1yINCCNhgBXDbleJXNhbQR7CBsQjDKAQQjkYYYrGEDBvaafEChezDQHA8h-Yp0kGBJrCeD1MBsKDwhAZLrVCBgYRsKSg4DBPCs-bkKXCQTkUh0QIAX0CGhkYECKQGQ1GiOEyNRW0I8PZUi0qy+3UCQpFYsCwAF3TAgjKeGd1XIggARggPd8bXQ7gGbdlyK18qGw+QfdzGtGbeQpInuhHU16oBnVerNdqQLrYfqkSj2FttnRGuaRMJhiEvp7AtYCWD2gBlb2UQKJQIACgJCvgAEpu4zuvLFXRe1A2KR4cYbBh4u1-AgF+QAEKNACSUF7KRrKSHUtdZQAahALv3O8Oh5FG83QaeOBeLt2+xKNIIKIQpXjahQWJZCqI6JGO1TPr2wAqlK8iNtUwZQTB0p7OQ+4gO4CqBAAYt+5CUkOx7wUUX4-p4voIK+5xQeqeG-oE-7wIBnCqkRgbdKod7pOx2SPrRZEUfAVHvjRpH4X+EAAeQQGsaOxHen68BIbBxHhpGe6qUU0HZkmUjKYEcE8WGan6ZQqHobhFBHmxxlJlOmk2k6Rm2UUnCkKUpDlEgfagaErKCW2opoZ+dESVJMkgTpLlgk0CDeSkc5SNwUjeSKZSUFIKRRcZMEOWmMroQAgvCEaikeeXZDZ0WcZpVXGbG8b7s53TaXlYmkq6wi9tOvkVayenaQZfXhnug1mWhUAYONhHZTGo0xc08DxSA5x0BAlAALSEPKpBLYEHBsOcUgiCkqpSuN04YPCxBSAA-CsRjwBgWhJeQM19TVzXVFxLl1RxXEPpwLYKQggUOj2omhQxklMdJLEgXJzXEOQHaDlBmntd58gYDj7WqBgyVob2ghSj6vVfUUjHMdx0WBLdgSCFdN33YYxjPZJBIYLAs6CAg7hovKtS9j6TPwHdD1sy9BI-bTgTeSL11iyzj3s69XM83zAuCELjOK+LrNPVLb21bNVNwxw3mOGbQFRSB95GcS2LEUu7ToYWcKkAqG1ifQYtsOU8I1sawzteVzVTa0HDdVACqCL5rYozekM-t5MfehgaeM7zsBhbDQHecm8LwKxMvFLS0j0n8NLqVXcZQI0C0IJyGIbec0ARt5dyKIoACk-LsfYz62lA9SHlSNLPlXwx140mTV4wYT25YxBkObuimIoSCKBtaAAGxbyAMEGI9NAUpY1i2OQNDnwL2hizQPq+iQh94Mfxinx8N82GkV+mIfqgqiAA). 

- Added [`@hyperapp/html`](https://github.com/jorgebucaran/hyperapp/tree/master/pkg/html) to help tidy up the code a bit. (Optional)
- Fixed a latent bug in `sortIt`. 
  - [Sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) sorts arrays in place, unfortunately, so you need to make a copy before using it. 
- Renamed a few functions.
  - `sortIt`→`tableSort`
  - `tableOfCatFacts`→`factsTableView`.
- Modified `setState` to use new `mainView` function.

**Comment by mike-ward** [comment]
Another [variation](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANOLAE4D2UBqA2gAyF0C6xAZgJYxho2gB2AQ1wQ0mHPiIhY5PolmiAPGDLsADvAAE8AJ6qIAXgA6IXOSQBXGMYB8hvho3tcq8qU3ANWQlogAPeN6qAvCwWBoAvhqsFLgaxjjwqmCoAPQp5nyqANYA5hjSuClg5nqkHHwQxnZ2DtJ8YJqQ8ADK8MEQGvoaABQN7QCUnbb2DhpBIVjdNaMOSOSw5sKyGDkQ8ACiMEvwAELaAJJIUyACqqrG-YTTM5PGuALsfMbewOHeNNcznt0A5FgAjD8Xm8fP5jgBhYIaABiAgQYAul0+M1YcPgYAAKgIAEYwXptRD9ZEaJhEkYOMnTVgZBDsGRRNGYnF4vqEjTAT6kNbmUj2W4gNq4ypEdkgjQfcmjSY-eBYCACJBA0XefnwUjPZXi4kOVVYDWvbyIMHGWEIRFXSU3Y6y-VxS1fGSwKDsWBZVA9Qb6awaMCueD7eD4gbebWjBraGDun4LUi+0julyPRCkH52r5fEFGwPGACC5llrnNod1+szfkDPwAqqoNAA1ciIMA-fpk9MOUlI+3S+DYszaJUGtNt1kQDCo+EYe6qbpIIbfYxq0vvIdt74yxUvcORjQ-ADuWHYiAAtGAgrAIO6+K57lAfmWwUgMFmWxbVzrfvAN5qszOMOZIKQAD8GCCMIY7sLG8AvqG77rgO96Bo+JQAG4NhAYAtqGHbEq2oyktM4TVCM1J8LS9Jxv6gYjoMHKSk0rTtN0tHpuO6LujQGCcSOY6MkwGAUd03QCN42Ket63FIBBcDwHS9ihoBGgCH+AHAaBo4cJBGBQPMAgwOC5DOAIXLdNiykQEBIFCOpEENLh6buqZ-7mapVngZp2mwLpED6YZxlKU5FlqW5tmdumklcmRfDugAhBJUmRZ84S4YRTwjAIvh0gikorGsvwJEkqQpJ58BHqx2DmeQWTmKcqj5AZKSsU2dkaE+cp8DOwQCHO9EEhATGNe6SCdRgQ1tBgulQN44XSbJ7pquYEBJf0ADcdgKEUKjqMMCj3I8jhIEYJxnDY627XwwySJAMCRdw6AAMz-KgdAgG8-BWaIGAAFbcMQdRyPAoiSAUqicOZojYji0AvYQb3CB9sBgD9UgyP9gPhCwIDOnwWS3bwIBqaI6WZZOjxfUjPLUCA+XJGkGTZHkBQpET5BgAAAnQGAAEwc3QKSSQ0TMZSzJN8GTkg6HoojKKQagA69+PvegToCIjXBgPkiOSBTojU4Vyuq+h6tIBARVQCrYBqxrSMSyI6BbiI6PhEAA)

Couple of questions:
```
 const setState = (state) =>
    patch(
      document.getElementById("app"),
      h("main", {}, [
        h('h1', {}, text("Cat Facts")),
        factsTable(state)
      ])
    )
```

- `h("main", {}, [` doesn't write the `id` attribute and yet it's in the updated DOM after sorting. Seems like the patched DOM would be missing the `id` attribute since I didn't include it in my VDOM. How does it get in there?

- Should `patch` be modified to take a VDOM or an array of VDOM's?

- In asking the last question I realized that there's no place to put the `id` attribute with just an array of VDOM's. I think I was expecting `patch` to nest the VDOM in the DOM node.

Really like the simplicity and just noodling around to understand it better.

**Comment by jorgebucaran** [comment]
1) The `id` is unknown to Superfine (since it's not declared in your view/VDOM) and Superfine won't touch any attributes it doesn't know about—how well-mannered! It gets there because Superfine recycles the existing `main` element instead of throwing it away and creating it from scratch.
2) Hmm, I don't think so. While some VDOMs might behave like that, Superfine works by replacing or patching the DOM root/element (in this case patching because your HTML element matches the root element in your VDOM).
3) Gotcha. I think I covered this above.

Let me know if this covers everything for you. 🙏 


> Really like the simplicity and just noodling around to understand it better.

That's awesome. Thank you!

**Comment by mike-ward** [comment]
An overload to the `h()` API that takes its children as splat arguments would be helpful. 

`h(type, props, ...children)`

[Mithril JS](https://mithril.js.org/hyperscript.html) does this and I've found it useful.

**Comment by jorgebucaran** [comment]
I believe that's easy enough to implement in userland and import into your project. I also have a dislike variadic functions.
