### ISSUE TITLE
Custom Elements Everywhere

### ISSUE THREAD

**Issue by mindplay-dk** [jorgebucaran/superfine#63]
This seems like a good initiative:

https://custom-elements-everywhere.com/

Demonstrating support for custom elements would probably be a good move to make sure we're ready for the future - as well as to promote the library.

(`hyperHTML` is the only other lightweight framework on the list, and one of the only ones passing all the tests.)

**Comment by JorgeBucaran** [comment]
@mindplay-dk How hard could it be to get on that list? Looks doable.

**Comment by Pyrolistical** [comment]
Do we expect picodom to be able to pass all the tests? is it just a matter of making a PR to https://github.com/webcomponents/custom-elements-everywhere

**Comment by JorgeBucaran** [comment]
@Pyrolistical Possibly! I admit I haven't had time to look into this.

**Comment by jorgebucaran** [comment]
There's nothing special we need to do to support custom elements, but I'm tracking down shadow DOM support in https://github.com/jorgebucaran/superfine/issues/134.
