### ISSUE TITLE
Add types for VDOM events.

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/superfine#65]
We have 3 VDOM events at the moment:

- oncreate(element)
- onupdate(element, oldProps)
- onremove(element): remove

But they are not typed in the type declarations.

**Comment by mindplay-dk** [comment]
I haven't been able to figure out the right syntax for this - hopefully a solution can be used as a reference to solve #36 more broadly, which I'd be happy to help with :-)

**Comment by pickle-ts** [comment]
In case it's of any help, I'm maintaining a typescript version of ultradom (here: https://github.com/pickle-ts/pickle/blob/master/src/dom.ts ). The types in question:

export interface VAttributes extends VLifecycle {
    key?: string | number
}

export interface VLifecycle {
    oncreate? (element: Element, attributes?: VAttributes) : void
    onupdate? (element: Element, attributes?: VAttributes) : void
    onremove? (element: Element, remove: () => void) : void
    ondestroy? (element: Element) : void
}

By separating out lifecycle into an interface, I'm able to reuse this interface for a function that composes lifecycle events:
https://github.com/pickle-ts/pickle/blob/master/src/lifecycle.ts (very handy for animations!)

Maybe some interesting background here. I wrote an HTML DOM generator in C# a while ago ( https://github.com/hyperlinq/hyperlinq ) . C# generics are very expressive, so I was even able to statically type check that a particular attribute was legal for a particular element. I might investigate whether something similar is possible with typescript/ultradom in the future. I'm just like everyone else rather bogged down in work right now!

**Comment by jorgebucaran** [comment]
Superfine 7 dropped lifecycle events.
